### PR TITLE
Automatically process index.js to data.txt

### PR DESCRIPTION
**Pull request by m-a-x-s-e-e-l-i-g**
> **Note** - Since this is a public repository, make sure that we're not publishing private data in the code, commit comments, or this PR.

> **Note for reviewers** - Please add a 2nd reviewer if the PR affects more than 15 files or 100 lines (not counting
  `package-lock.json`), if it incurs significant risk, or if it is going through a 2nd review+fix cycle.

## 📚 Context/Description Behind The Change

I thought it could be handy to be able to use this awesome and extensive list in projects that don't use .js.

## 🚨 Potential Risks & What To Monitor After Deployment

- 💥Many explosions💥  
- Negative feedback from more experienced developers.

## 🧑‍🔬 How Has This Been Tested?

Just ran the workflow and it did what it needed to do.

## 🚚 Release Plan

1. Add Github `USERNAME` as an [action secret](https://github.com/mixmaxhq/role-based-email-addresses/settings/secrets/actions/new).
2. Pray 🙏

### CODE REVIEW

**Comment by raphaelbs** [comment]
Assigning @jsalvata to give feedback on this

**Comment by jsalvata** [comment]
Hi Max. Thanks for your contribution. I just need to verify that this won't be at odds with our regular CI/CD process (which is not yet enabled for this project).

In the meantime, would you mind adding a note in the README about this new `data.txt` file?

**Comment by jsalvata** [comment]
Update: no issue w.r.t. the CI/CD process.

**Comment by jsalvata** [comment]
Closing this. Please reopen if/when the README is updated to reflect this change.

**Pull request closed without merging**
