### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by grab76**
Add 'communications' and 'corporatesales'

### CODE REVIEW

**Comment by bradvogel** [comment]
thanks!

**Comment by bradvogel** [comment]
I have some more to add, then I'll publish a new npm version

**Comment by grab76** [comment]
"I have some more to add, then I'll publish a new npm version" : Me too, I develop an API to validate email.

So I will update your file soon.

**Comment by bradvogel** [comment]
Sounds great. Just curious - where are you sourcing yours?

**Comment by grab76** [comment]
I developed an infrastructure and I extract data from difference sources.
I developed an algorithm to detect role based email.

2016-11-25 23:40 GMT+01:00 Brad Vogel <notifications@github.com>:

**Comment by bradvogel** [comment]
Published as 1.0.4

**Pull request merged**
